### ISSUE TITLE
Seemingly inconsistent information in two documentation pages

### ISSUE THREAD

**Issue by jh2217** [flatredball/FlatRedBallDocs#10]
In the page on [NamedTileOrderedIndexes](https://docs.flatredball.com/flatredball/tiled-plugin/flatredball-tilegraphics-mapdrawablebatch/namedtileorderedindexes), the documentation states that tile ordered indices start from the bottom left of a tile map.

In the page on [PaintTile](https://docs.flatredball.com/flatredball/tiled-plugin/flatredball-tilegraphics-mapdrawablebatch/painttile), the documentation states that `orderedTileIndex` start from the top left of a tile map.

Either one of these pages are wrong, or there exist two very similar indexing schemes that start from different corners of the map.

Screenshot from [NamedTileOrderedIndexes](https://docs.flatredball.com/flatredball/tiled-plugin/flatredball-tilegraphics-mapdrawablebatch/namedtileorderedindexes)
![image1](https://github.com/flatredball/FlatRedBallDocs/assets/31798972/f03fc44d-b02f-4f46-aad8-353c99627567)

Screenshot from [PaintTile](https://docs.flatredball.com/flatredball/tiled-plugin/flatredball-tilegraphics-mapdrawablebatch/painttile)
![image2](https://github.com/flatredball/FlatRedBallDocs/assets/31798972/8a377f43-4846-4c24-971e-116888392822)

**Comment by vchelaru** [comment]
Docs have been updated
