### ISSUE TITLE
Docs Migration 2: Fix side navigation

### ISSUE THREAD

**Issue by profexorgeek** [flatredball/FlatRedBallDocs#2]
The side navigation needs to be manually fixed as a special file for GitBook. The order should match the order on the current FRB.com site.

**Comment by profexorgeek** [comment]
@vchelaru is this done? It looks like you made progress on this!

I mean, it may never be "done done", but is it done for first pass?

**Comment by vchelaru** [comment]
Not done yet, still working on it bit by bit.
