### ISSUE TITLE
Automatable fixes

### ISSUE THREAD

**Issue by vchelaru** [flatredball/FlatRedBallDocs#8]
There are some things that could be fixed through automation. Since ultimately this is all markdown files in a repository, I or Justin could do these; however, I will be focusing on the fixes that require manual changes so maybe Justin can do these automated fixes.

## Checklist
- [x] Gif conversion
- [x] API Capitalization

## GIF <Figure> Conversion

Currently GIFs are inlined, but they should be their own block. The syntax that Gitbook expects is:

```
<figure><img src="../../../media/2021-04-2021_April_14_192104.gif" alt=""><figcaption></figcaption></figure>
```

The old syntax was:

```
[![](../../../media/2021-04-2021\_April\_14\_192104.gif)](../../../media/2021-04-2021\_April\_14\_192104.gif)
```

For more examples look in any commit that has GIF changes and search for ".gif". For example, https://github.com/flatredball/FlatRedBallDocs/commit/c31bb3d9044a495bdab8ed5eb7e37cf453ef75db

## API capitalization

Most API documentation follows the namespace structure of FlatRedBall. The titles of the pages should be the namespace or object. Currently the structure here has lower-case names for all the classes and namespaces, but FlatRedBall (and C#) use upper case.

![image](https://github.com/flatredball/FlatRedBallDocs/assets/729631/98d85736-7b8e-47b8-9ad3-19bc5192fce3)

An automated fix here would be to search through all of the summary.md files and see if their children match namespaces and classes. This automation would require loading the FlatRedBall.dll and getting the types and comparing. If a match is found, but the summary link is lower-case, make it upper case.

**Comment by profexorgeek** [comment]
I edited your comment to have a checklist at the top. The gif conversion part of this is done.

Regarding the API capitalization... the loading of the FRB dll sounds really complicated. We could start by just capitalizing the first letter of every page. For the rest of the camel-casing... we could do that over time. You'd have to write a whole custom application to loop through every page and match it against things reflected from the API.

If you or I were going to go through the trouble to do all of that, we should probably just move to a system where we automatically extract methods, XML comments, etc to render API docs. That's what Microsoft does for API docs.
